### ISSUE TITLE
How to make preprocessing steps for own data set? 

### ISSUE THREAD

**Issue by nang-kham** [pioneerAlpha/BanglaText2ImageGeneration#1]
Dear author, may you share your scripts about preprocessing the dataset

**Comment by saba56** [comment]
Hello @nang-kham ....Were you able to work with your own dataset...

**Comment by nang-kham** [comment]
> Hello @saba56 Now I am ok for working with my own dataset.

**Comment by nasim-aust** [comment]
> Dear author, may you share your scripts about preprocessing the dataset
Not yet. Will be available in future.
